// First-page thumbnails and full-size viewing for attached PDFs, via pdf.js.
//
// Why pdf.js rather than an <iframe src={pdf}>: desktop browsers render PDFs
// in an iframe, Android Chrome does not (it shows a blank box or a download
// prompt). Since most residents are on phones, an iframe preview would be
// blank for roughly half of them. pdf.js draws to a canvas, which works
// everywhere.
//
// It's a heavy library, so it is only imported the first time a PDF actually
// needs drawing — a board with no PDFs on it never downloads it.

let pdfjsPromise = null;

function getPdfjs() {
  if (!pdfjsPromise) {
    pdfjsPromise = (async () => {
      const [pdfjs, worker] = await Promise.all([
        import('pdfjs-dist'),
        import('pdfjs-dist/build/pdf.worker.min.mjs?url'),
      ]);
      pdfjs.GlobalWorkerOptions.workerSrc = worker.default;
      return pdfjs;
    })();
  }
  return pdfjsPromise;
}

// Support files pdf.js fetches on demand: fonts for PDFs that don't embed
// their own (common in anything generated by Word), and the wasm decoders for
// scanner-produced images. Copied into public/pdfjs by vite.config.js.
const ASSET_OPTIONS = {
  standardFontDataUrl: '/pdfjs/standard_fonts/',
  wasmUrl: '/pdfjs/wasm/',
  iccUrl: '/pdfjs/iccs/',
};

// One parsed document per URL: the board card thumbnail and the big view of
// the same file share it instead of downloading and parsing twice.
const documents = new Map();

export function loadPdf(url) {
  if (!documents.has(url)) {
    const promise = getPdfjs()
      .then((pdfjs) => pdfjs.getDocument({ url, ...ASSET_OPTIONS }).promise)
      .catch((err) => {
        documents.delete(url); // let a later attempt retry a transient failure
        throw err;
      });
    documents.set(url, promise);
  }
  return documents.get(url);
}

// Draws one page into a canvas, sized to fit `maxWidth` CSS pixels and scaled
// up for the device's pixel ratio so it isn't soft on a phone screen.
export async function renderPageToCanvas(pdf, pageNumber, canvas, maxWidth) {
  const page = await pdf.getPage(pageNumber);
  const unscaled = page.getViewport({ scale: 1 });
  const ratio = Math.min(window.devicePixelRatio || 1, 2);
  const viewport = page.getViewport({ scale: (maxWidth / unscaled.width) * ratio });

  canvas.width = Math.floor(viewport.width);
  canvas.height = Math.floor(viewport.height);
  canvas.style.width = `${Math.floor(viewport.width / ratio)}px`;
  canvas.style.height = `${Math.floor(viewport.height / ratio)}px`;

  await page.render({ canvas, viewport }).promise;
}
